# This is a TOML document.

title = "TOML Example"

[client]
    name = "client_name"

## MQTT input config
[input.mqtt]
    host = "<host>"
    port = <port>
    user = "<user>"
    password = "<password>"
    topic = "<topic/name/#>"

## zabbix input config
[input.zabbix]
    url = "url"
    user = "user"
    password = "password"
    repeat_time = time[s]

	[[input.zabbix.group]]
    	gname = "group name"

	[[input.zabbix.host]]
    	hname = "host name"

	[[input.zabbix.host]]
    	hname = "host name"

## rabbit HA-mode input  queue config
[input.rabbitmq]
    vhost = "host"
    queue_name = "queue_name"
    username = "username"
    password  = "password"
    ssl = true/false
    [input.rabbitmq.ssl_options]
	"ca_certs" = "/ssl/cacert.pem"
	"certfile" = "/ssl/cert.pem"
	"keyfile" =  "/ssl/key.pem"

    [[input.rabbitmq.host]]
        url = "url/ip"
        port = 69

    [[input.rabbitmq.host]]
        url = "url/ip"
        port = 68

[transform.mssql]
    url = "zzz.zzz.zzz.zzz"
    database = "database"
    username = "username"
    password = "password"

## rabbit HA-mode output queue config
[output.rabbitmq]
    vhost = "host"
    queue_name = "queue_name"
    username = "username"
    password  = "password"
    ssl = true/false

    [output.rabbitmq.ssl_options]
	"ca_certs" = "/ssl/cacert.pem"
	"certfile" = "/ssl/cert.pem"
	"keyfile" =  "/ssl/key.pem"

    [[output.rabbitmq.host]]
        url = "url/ip"
        port = 69

    [[output.rabbitmq.host]]
        url = "url/ip"
        port = 68

## influx output config
[output.influxdb]
  url = "influx.db"
  port = "69"
  database = "dbname"

  ## Retention policy to write to. Empty string writes to the default rp.
  retention_policy = ""
  ## Write consistency (clusters only), can be: "any", "one", "quorum", "all"
  write_consistency = "any"

  ## Write timeout (for the InfluxDB client), formatted as a string.
  ## If not provided, will default to 5s. 0s means no timeout (not recommended).
  timeout = "5s"
  username = "username"
  password = "password"
  ## Set the user agent for HTTP POSTs (can be useful for log differentiation)
  # user_agent = "telegraf"
  ## Set UDP payload size, defaults to InfluxDB UDP Client default (512 bytes)
  # udp_payload = 512

  precision = "s"

  ## Optional SSL Config
  # ssl_ca = "/etc/telegraf/ca.pem"
  # ssl_cert = "/etc/telegraf/cert.pem"
  # ssl_key = "/etc/telegraf/key.pem"
  ## Use SSL but skip chain & host verification
  # insecure_skip_verify = false

## MQTT output config
[output.mqtt]
    host = "<host>"
    port = <port>
    user = "<user>"
    password = "<password>"
    topic = "<topic/name/#>"
